version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile # Use the Dockerfile for your FastAPI app
    container_name: my-fastapi-app
    ports:
      - "8000:8000" # Map your FastAPI app's port to a host port
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - shared_network
    volumes:
      - /home/ubuntu/personalized_kids_book/public:/public

  mongodb:
    image: mongo:latest
    container_name: personalized_kids_book-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplePassword
      MONGO_INITDB_DATABASE: personalized_kids_book
    volumes:
      - mongodb_data:/data/db
    networks:
      - shared_network



volumes:
  mongodb_data:

networks:
  shared_network:
    external: true

